### ISSUE TITLE
Comparing vs famous parsers

### ISSUE THREAD

**Issue by SC-One** [cthulhu-irl/parsi#44]
## Description
need add new benchmark functions (same situation) in benchmark dir to comparing vs famous parser libraries

## Goals
 compare vs : 
- rapidjson
- simdjson
- nlohman
-  TODO: add more ...

## Definition of Done
[ ] result of comparing with rapidjson
[ ] result of comparing with simdjson
[ ] result of comparing with nlohman
...

**Comment by cthulhu-irl** [comment]
Tasks are reserved for maintainers only. Requests are welcome in any form.

This is a parser combinator library and the mentioned other libraries to benchmark against are json parser libraries which are completely different.

Parsi currently doesn't have any json parsing features. It's under consideration, and so will be the suggested libraries to benchmark against when the json feature has made it into the parsi.

It's not applicable yet, therefore I'm closing this issue.
